parameters:
#    afsy_blackjack.example.class: Afsy\Bundle\BlackjackBundle\Example

services:
    jbnahan_school.student.repository:
        class: Broadway\EventSourcing\EventSourcingRepository
        arguments: [@broadway.event_store, @broadway.event_handling.event_bus, Jbnahan\Domain\School\Model\Student]

    jbnahan_school.student.command_handler:
        class: Jbnahan\Domain\School\CommandHandler\StudentEngineHandler
        arguments: ['@jbnahan_school.student.repository']
        tags:
            - { name: 'command_handler' }


    jbnahan_school.student_class.repository:
        class: Broadway\EventSourcing\EventSourcingRepository
        arguments: [@broadway.event_store, @broadway.event_handling.event_bus, Jbnahan\Domain\School\Model\StudentsClass]

    jbnahan_school.class.command_handler:
        class: Jbnahan\Domain\School\CommandHandler\ClassEngineHandler
        arguments: ['@jbnahan_school.student_class.repository']
        tags:
            - { name: 'command_handler' }
