services:
    afsy_blackjack.game_view.listener:
        class: Jbnahan\Domain\Scool\Listener\StudentViewListener
        arguments: [@doctrine]
        tags:
            - { name: lite_cqrs.event_handler }
