services:
    jbnahan_school.student_view.listener:
        class: Jbnahan\Domain\School\Listener\StudentViewListener
        arguments: [@doctrine]
        tags:
            - { name: lite_cqrs.event_handler }
