jbnahan_school_student_register:
    path:     /student/register
    defaults: { _controller: JbnahanSchoolBundle:Student:register }

jbnahan_school_student_show:
    path:     /student/show/{id}
    defaults: { _controller: JbnahanSchoolBundle:Student:show }

jbnahan_school_student_subscription:
    path:     /student/subscription/{id}
    defaults: { _controller: JbnahanSchoolBundle:Student:subscription }

jbnahan_school_class_register:
    path:     /class/open
    defaults: { _controller: JbnahanSchoolBundle:Class:open }

jbnahan_school_class_show:
    path:     /class/show/{id}
    defaults: { _controller: JbnahanSchoolBundle:Class:show }

jbnahan_school_class_rename:
    path:     /class/rename/{id}
    defaults: { _controller: JbnahanSchoolBundle:Class:rename }