jbnahan_school_student_register:
    path:     /student/register
    defaults: { _controller: JbnahanSchoolBundle:Student:register }

jbnahan_school_student_show:
    path:     /student/show/{id}
    defaults: { _controller: JbnahanSchoolBundle:Student:show }
