parameters:
#    jbnahan_school.example.class: Jbnahan\Bundle\SchoolBundle\Example

services:
#    jbnahan_school.example:
#        class: %jbnahan_school.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
