
#Jbnahan\Domain\School\Command\RegisterStudentCommand:
#    properties:
#        firstName:
#            - NotBlank: ~
#        lastName:
#            - NotBlank: ~
#        bornOn:
#            - Date: ~