Jbnahan\Bundle\ScoolBundle\Entity\StudentsClass:
    type: entity
    table: class_of_students_view
    repositoryClass: Jbnahan\Bundle\ScoolBundle\Entity\StudentsClassRepository
    id:
        id:
            type: string
            length: 36
            id: true
    fields:
        name:
            type: string
            length: 255
        grade:
            type: string
            length: 255
        version:
            type: integer
        students:
            type: array
    lifecycleCallbacks: {  }
