Jbnahan\Bundle\SchoolBundle\Entity\Student:
    type: entity
    table: students_view
    repositoryClass: Jbnahan\Bundle\SchoolBundle\Entity\StudentRepository
    id:
        id:
            type: string
            length: 36
            id: true
    fields:
        firstName:
            type: string
            length: 255
        lastName:
            type: string
            length: 255
        version:
            type: integer
        bornOn:
            type: datetime
    lifecycleCallbacks: {  }
