<?php

namespace Jbnahan\Bundle\SchoolBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StudentSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StudentSubscriptionRepository extends EntityRepository
{
}
